### ISSUE TITLE
无法生成 support 64-bit abi 任务

### ISSUE THREAD

**Issue by kezhian** [pengxurui/EasyPrivacy#4]
### 问题如下

```java
class Bit64Feature {

    void apply(Project project) {
        project.afterEvaluate {
            // 1. Find the task merge[BuildVariants]NativeLibs
            Task mergeNativeTask = null;
            for (Task task : project.getTasks()) {
                
                if (task.name.startsWith("merge") && task.name.endsWith("NativeLibs")) {
                    mergeNativeTask = task
                }
            }

            if (null == mergeNativeTask) {
                return
            }

…………
```

调试了下，project.getTasks() 返回的是 TaskContainer 对象，会导致 mergeNativeTask 为空的，生成不了检查 abi 的task的

使用的 gradle 版本和 gradle 插件版本如下

```gradle
compile 'com.android.tools.build:gradle:4.1.2'
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip
```

**Comment by bhd119** [comment]
我这边也是用不了：
classpath 'com.android.tools.build:gradle:3.5.3'
distributionUrl=https\://services.gradle.org/distributions/gradle-6.2-all.zip

**Comment by pengxurui** [comment]
classpath 'com.android.tools.build:gradle:3.5.3'
distributionUrl=https://services.gradle.org/distributions/gradle-6.2-all.zip

![image](https://user-images.githubusercontent.com/25008934/146640715-88f6b40f-9d46-41f6-8ca6-417e6671ab9b.png)

![image](https://user-images.githubusercontent.com/25008934/146640734-7c833415-23f3-4b42-baf6-304911341337.png)


感谢测试。以上配置这边测试可以生成 task，可以检查下是否找对位置哈，或者提供更多信息方便排查，谢谢。

**Comment by pengxurui** [comment]
compile 'com.android.tools.build:gradle:4.1.2'
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip

![image](https://user-images.githubusercontent.com/25008934/146640774-1cc1a4d2-2421-4dd5-a475-bed911e685de.png)

![image](https://user-images.githubusercontent.com/25008934/146640782-4aa6f44e-6fa7-4d62-8574-7795995ad3e4.png)

感谢测试。以上配置这边测试可以生成 task，可以检查下是否找对位置哈，或者提供更多信息方便排查，谢谢。

**Comment by TmRobust** [comment]
AS 版本 Arctic Fox 2020 3.1 patch 3版本

compile 'com.android.tools.build:gradle:4.1.2'
distributionUrl=https://services.gradle.org/distributions/gradle-6.5-all.zip

没有生成task

**Comment by kezhian** [comment]
## 问题已处理

Bit64Feature 类在自定义 Plugin 类 apply 方法中引用排列的问题

以下编写是存在问题的

```gradle
class ApplicationPlugin extends BasePlugin {

    @Override
    void apply(Project project) {
        super.apply(project)
        // 在第一行引入
        new Bit64Feature().apply(project)
        applyAndroidApplication()
        applyAndroidSetting()
        applyApplicationSetting()
        applyKotlin()
        applyDependencies()
        ……
    }
}
```

以下编写则没有问题

```gradle
class ApplicationPlugin extends BasePlugin {

    @Override
    void apply(Project project) {
        super.apply(project） 
        applyAndroidApplication()
        applyAndroidSetting()
        applyApplicationSetting()
        applyKotlin()
        applyDependencies()
        //最后一行
        new Bit64Feature().apply(project)
        ……
    }
}
```

**Comment by pengxurui** [comment]
感谢测试，你这边的 issue 是自定义插件出问题是吗

**Comment by kezhian** [comment]
是的

**Comment by Myxiaoli** [comment]
![image](https://user-images.githubusercontent.com/28335346/146883778-30105903-56bd-4b7f-bc44-97eccab4e8f3.png)
![image](https://user-images.githubusercontent.com/28335346/146883894-cf84224f-a3e2-49fb-84ee-a8a3eb64c405.png)
可以找到这个task,但是执行这个task会一直报这个错误，为什么呢？

**Comment by pengxurui** [comment]
@Myxiaoli 感谢测试。这个问题是 Android Studio 4.1.2 版本兼容问题，EasyPrivacy 最新版本 v1.0.5 已经兼容哦。
