### ISSUE TITLE
Privacy和PrivacyFeature

### ISSUE THREAD

**Issue by DongDian455** [pengxurui/EasyPrivacy#7]
你好，请问下这两个类的作用是什么？
是为了后续增加配置使用吗，刚学groovy不久，看得不是很明白

**Comment by pengxurui** [comment]
感谢测试。Privacy 是自定义的 Extension，不过在源码中没有真正调用到。PrivacyFeature 就是普通的类，主要封装了跟 64位兼容检测相关的能力
