### ISSUE TITLE
Task '64-bit' not found in project ':app'.

### ISSUE THREAD

**Issue by ming198** [pengxurui/EasyPrivacy#8]
你好这个错误是怎么回事?

**Comment by ming198** [comment]
![image](https://user-images.githubusercontent.com/57481511/147739784-787817c3-b1f9-40cd-9a3a-18aedffc6c00.png)

**Comment by pengxurui** [comment]
感谢测试。这个问题是 Android Studio 4.1.2 版本兼容问题，EasyPrivacy 最新版本 v1.0.5 已经兼容哦。

**Comment by pengxurui** [comment]
@ming198 感谢测试，这问题已经修复
